# Generated by Django 5.2.3 on 2025-07-07 11:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="margin",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Ex.: 20 = 20%",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Margem (%)",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="sale_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Preço de Venda",
            ),
        ),
    ]
