# Generated by Django 5.2.3 on 2025-07-07 20:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderitem_cost_price_orderitem_margin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Preço de Custo",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="margin",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="Ex.: 20 = 20%",
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Margem (%)",
            ),
        ),
    ]
