# Generated by Django 5.2.3 on 2025-07-09 21:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_businessunit_ordertype_port_project_and_more"),
        ("orders", "0003_alter_orderitem_cost_price_alter_orderitem_margin"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="asap",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="business_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.businessunit",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="down_payment",
            field=models.DecimalField(
                decimal_places=6,
                default=30,
                help_text="Ex.: 20 = 20%",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.ordertype",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="pod",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders_as_pod",
                to="core.port",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="pol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders_as_pol",
                to="core.port",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.project",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="required_schedule",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="sales_representative",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.salesrepresentative",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="usd_brl",
            field=models.DecimalField(
                decimal_places=6,
                default=5.6,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="usd_rmb",
            field=models.DecimalField(
                decimal_places=6,
                default=7.2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="validity",
            field=models.DateTimeField(default="2025-07-27"),
            preserve_default=False,
        ),
    ]
