# Generated by Django 5.2.3 on 2025-07-09 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_businessunit_ordertype_port_project_and_more"),
        ("orders", "0004_order_asap_order_business_unit_order_down_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="business_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.businessunit"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.ordertype"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="pod",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders_as_pod",
                to="core.port",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="pol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders_as_pol",
                to="core.port",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.project"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="sales_representative",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.salesrepresentative",
            ),
        ),
    ]
