# Generated by Django 5.2.3 on 2025-07-10 19:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_business_unit_alter_order_order_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="cost_price_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Preço de Custo em Dólar",
            ),
        ),
    ]
