# Generated by Django 5.2.3 on 2025-07-14 14:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_orderitem_cost_price_usd"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batchstage",
            options={
                "ordering": ["estimated_completion"],
                "verbose_name": "Batch Stage",
                "verbose_name_plural": "Batch Stages",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="is_locked",
            field=models.BooleanField(
                default=False, help_text="No changes allowed when true"
            ),
        ),
        migrations.AlterField(
            model_name="batchstage",
            name="actual_completion",
            field=models.DateField(blank=True, null=True, verbose_name="Actual Date"),
        ),
        migrations.AlterField(
            model_name="batchstage",
            name="estimated_completion",
            field=models.DateField(blank=True, null=True, verbose_name="Estimed Date"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Cost Price",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="cost_price_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Dolar Cost Price",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="margin",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="Ex.: 20 = 20%",
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Margin (%)",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="sale_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Sale Price",
            ),
        ),
    ]
