# Generated by Django 5.2.3 on 2025-07-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_stage_alter_batchstage_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchstage",
            name="name",
            field=models.CharField(default="rr1", max_length=100, verbose_name="Etapa"),
            preserve_default=False,
        ),
    ]
