# Generated by Django 5.2.3 on 2025-07-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_alter_batchstage_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchstage",
            name="name",
            field=models.CharField(max_length=100, null=True, verbose_name="Etapa"),
        ),
    ]
