# Generated by Django 5.2.3 on 2025-07-17 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_alter_batchstage_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batchstage",
            name="name",
        ),
        migrations.AddField(
            model_name="batchstage",
            name="stage",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batch_stage",
                to="orders.stage",
            ),
            preserve_default=False,
        ),
    ]
