# Generated by Django 5.2.3 on 2025-07-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_remove_batchstage_name_batchstage_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchstage",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
