# Generated by Django 5.2.3 on 2025-07-22 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_alter_itempackagingversion_options_and_more"),
        ("orders", "0012_batchstage_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="packaging_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="inventory.itempackagingversion",
            ),
        ),
    ]
