# Generated by Django 5.2.3 on 2025-07-23 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_orderitem_packaging_version"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={"ordering": ["pk"]},
        ),
    ]
