# Generated by Django 5.2.3 on 2025-07-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_alter_orderitem_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batchstage",
            options={
                "ordering": ["stage__sort_order"],
                "verbose_name": "Batch Stage",
                "verbose_name_plural": "Batch Stages",
            },
        ),
        migrations.AlterModelOptions(
            name="stage",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "Stage",
                "verbose_name_plural": "Stages",
            },
        ),
        migrations.AddField(
            model_name="stage",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
