# Generated by Django 5.2.3 on 2025-10-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_orderbatch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbatch',
            name='status',
            field=models.CharField(choices=[('negotiation', 'In Negotiation'), ('production', 'In Production'), ('pre', 'Pre Shipment'), ('transit', 'In Transit'), ('delivered', 'Delivered'), ('stb', 'Stand by'), ('canceled', 'Canceled')], default='created', max_length=20),
        ),
    ]
