services:

    app:
        build: .
        env_file:
            - .env
        restart: always
        ports:
            - 8000:8000
        depends_on:
            - db
        networks:
            - backend 

    db:
        build:
            context: .
            dockerfile: Dockerfile.postgres
        expose:
            - "5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        networks:
            - backend
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=agk_core

volumes:
    postgres_data:

networks:
  backend:
    driver: bridge