version: "3.9"

services:

    app:
        build: .
        env_file:
            - .env
        restart: always
        ports:
            - 8000:8000
        depends_on:
            db:
                condition: service_healthy
        networks:
            - backend 

    db:
        build:
            context: .
            dockerfile: Dockerfile.postgres
        expose:
            - "5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
            - ./docker-postgres.conf:/var/lib/postgresql/data/postgresql.conf
            - ./certs/server.crt:/var/lib/postgresql/server.crt:ro
            - ./certs/server.key:/var/lib/postgresql/server.key:ro
        networks:
            - backend
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=agk_core
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d agk_core"]
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:

networks:
  backend:
    driver: bridge