FROM postgres:15

# Copia o arquivo diretamente da raiz do projeto
COPY ./postgresql.conf /etc/postgresql/postgresql.conf

# Define a execução do postgres com o arquivo customizado
CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
