# Generated by Django 5.2.3 on 2025-07-14 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0007_alter_batchstage_options_order_is_locked_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payment Condition",
                "verbose_name_plural": "Payment Conditions",
            },
        ),
        migrations.CreateModel(
            name="ProformaInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("usd_rmb", models.DecimalField(decimal_places=4, max_digits=10)),
                ("payment_terms", models.CharField(max_length=255)),
                (
                    "deposit_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        help_text="Arquivo PDF gerado da Proforma Invoice",
                        null=True,
                        upload_to="proforma_invoices/",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proforma",
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
