# Generated by Django 5.2.3 on 2025-07-14 18:29

import apps.finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proformainvoice",
            name="pdf",
            field=models.FileField(
                blank=True,
                help_text="Arquivo PDF gerado da Proforma Invoice",
                null=True,
                upload_to=apps.finance.models.proforma_invoice_upload_path,
            ),
        ),
    ]
