# Generated by Django 5.2.3 on 2025-06-24 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_item_chain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="model_application",
        ),
        migrations.CreateModel(
            name="ItemModelApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=100)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inventory.item"
                    ),
                ),
                (
                    "model_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.modelapplication",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="model_application",
            field=models.ManyToManyField(
                through="inventory.ItemModelApplication",
                to="inventory.modelapplication",
            ),
        ),
    ]
