# Generated by Django 5.2.3 on 2025-07-05 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0004_remove_item_model_application_itemmodelapplication_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="individual_packing_size",
            field=models.DecimalField(decimal_places=4, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="individual_packing_type",
            field=models.CharField(default=100, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="moq",
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="net_weight",
            field=models.DecimalField(decimal_places=4, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="package_gross_weight",
            field=models.DecimalField(decimal_places=4, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="packing_height",
            field=models.DecimalField(decimal_places=4, default=1000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="packing_lengh",
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="packing_width",
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itemmodelapplication",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itemmodelapplication",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
