# Generated by Django 5.2.3 on 2025-07-07 11:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("inventory", "0005_item_individual_packing_size_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerItemMargin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "margin",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ex.: 20 = 20%",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Margem padrão (%)",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.customer"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inventory.item"
                    ),
                ),
            ],
            options={
                "verbose_name": "Margem por Cliente/Item",
                "verbose_name_plural": "Margens por Cliente/Item",
                "unique_together": {("customer", "item")},
            },
        ),
    ]
