# Generated by Django 5.2.3 on 2025-07-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_customeritemmargin"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomerItemMargin",
        ),
    ]
