# Generated by Django 5.2.3 on 2025-07-22 11:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_delete_customeritemmargin"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemPackagingVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("net_weight", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "package_gross_weight",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                ("packing_lengh", models.DecimalField(decimal_places=4, max_digits=10)),
                ("packing_width", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "packing_height",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "individual_packing_size",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                ("individual_packing_type", models.CharField(max_length=200)),
                ("moq", models.IntegerField()),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packaging_versions",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "ordering": ["-valid_from"],
            },
        ),
    ]
