# Generated by Django 5.2.3 on 2025-07-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_itempackagingversion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itempackagingversion",
            options={},
        ),
        migrations.RemoveField(
            model_name="itempackagingversion",
            name="moq",
        ),
        migrations.AlterField(
            model_name="itempackagingversion",
            name="valid_from",
            field=models.DateTimeField(),
        ),
    ]
