# Generated by Django 5.2.3 on 2025-07-22 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_alter_itempackagingversion_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="individual_packing_size",
        ),
        migrations.RemoveField(
            model_name="item",
            name="individual_packing_type",
        ),
        migrations.RemoveField(
            model_name="item",
            name="net_weight",
        ),
        migrations.RemoveField(
            model_name="item",
            name="package_gross_weight",
        ),
        migrations.RemoveField(
            model_name="item",
            name="packing_height",
        ),
        migrations.RemoveField(
            model_name="item",
            name="packing_lengh",
        ),
        migrations.RemoveField(
            model_name="item",
            name="packing_width",
        ),
    ]
