# Generated by Django 5.2.3 on 2025-07-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_remove_item_individual_packing_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itempackagingversion",
            name="qty_per_master_box",
            field=models.PositiveBigIntegerField(default=10),
            preserve_default=False,
        ),
    ]
