# Generated by Django 5.2.3 on 2025-10-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_itempackagingversion_qty_per_master_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='version',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
