# Generated by Django 5.2.3 on 2025-10-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_versãocorrente_versãocuboroda_versãocxdireção_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VersãoRaio',
            new_name='VersaoCorrente',
        ),
        migrations.RenameModel(
            old_name='VersãoCuboRoda',
            new_name='VersaoCuboRoda',
        ),
        migrations.RenameModel(
            old_name='VersãoKitTrans',
            new_name='VersaoCxDirecao',
        ),
        migrations.RenameModel(
            old_name='VersãoCorrente',
            new_name='VersaoKitTrans',
        ),
        migrations.RenameModel(
            old_name='VersãoCxDireção',
            new_name='VersaoRaio',
        ),
    ]
