# Generated by Django 5.2.3 on 2025-10-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_rename_versãoraio_versaocorrente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='versao_raio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='versao_cubo_roda',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='versao_kit_trans',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='versao_corrente',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='versao_cx_direcao',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='VersaoCorrente',
        ),
        migrations.DeleteModel(
            name='VersaoCuboRoda',
        ),
        migrations.DeleteModel(
            name='VersaoCxDirecao',
        ),
        migrations.DeleteModel(
            name='VersaoKitTrans',
        ),
        migrations.DeleteModel(
            name='VersaoRaio',
        ),
    ]
