# Generated by Django 5.2.3 on 2025-10-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_item_versao_raio_alter_item_versao_cubo_roda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='english_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sales_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
