# Generated by Django 5.2.3 on 2025-10-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_item_english_description_item_sales_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='portuguese_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
