# Generated by Django 5.2.3 on 2025-07-23 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0014_alter_orderitem_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRE", "Pré‐Embarque"),
                            ("RDY", "Pronto p/ Embarque"),
                            ("SHP", "Embarcado"),
                        ],
                        default="PRE",
                        max_length=3,
                    ),
                ),
                ("shipping_date", models.DateField(blank=True, null=True)),
                ("carrier", models.CharField(blank=True, max_length=200)),
                ("tracking_number", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "workflow",
                    models.CharField(
                        choices=[("PRE", "Pré‐Embarque"), ("SHP", "Embarque Final")],
                        max_length=3,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["workflow", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FinalShipment",
            fields=[],
            options={
                "verbose_name": "Embarque Final",
                "verbose_name_plural": "Embarques Finais",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shipments.shipment",),
        ),
        migrations.CreateModel(
            name="PreShipment",
            fields=[],
            options={
                "verbose_name": "Pré‐Embarque",
                "verbose_name_plural": "Pré‐Embarques",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shipments.shipment",),
        ),
        migrations.CreateModel(
            name="ShipmentBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loaded_quantity", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="in_shipments",
                        to="orders.orderbatch",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment_batches",
                        to="shipments.shipment",
                    ),
                ),
            ],
            options={
                "unique_together": {("shipment", "order_batch")},
            },
        ),
        migrations.AddField(
            model_name="shipment",
            name="batches",
            field=models.ManyToManyField(
                related_name="shipments",
                through="shipments.ShipmentBatch",
                to="orders.orderbatch",
            ),
        ),
        migrations.CreateModel(
            name="ShipmentStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("date_done", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="shipment_stages/%Y/%m/%d/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="shipments.shipment",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shipments.stage",
                    ),
                ),
            ],
            options={
                "ordering": ["stage__sort_order"],
                "unique_together": {("shipment", "stage")},
            },
        ),
    ]
