# Generated by Django 5.2.3 on 2025-07-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FinalShipment",
        ),
        migrations.DeleteModel(
            name="PreShipment",
        ),
        migrations.RemoveField(
            model_name="shipmentstage",
            name="date_done",
        ),
        migrations.AddField(
            model_name="shipment",
            name="customer_reference",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Customer Ref."
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="leader",
            field=models.CharField(blank=True, max_length=100, verbose_name="Leader"),
        ),
        migrations.AddField(
            model_name="shipment",
            name="pol",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Port of Loading"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="signer",
            field=models.CharField(blank=True, max_length=100, verbose_name="Signer"),
        ),
        migrations.AddField(
            model_name="shipmentstage",
            name="actual_completion",
            field=models.DateField(blank=True, null=True, verbose_name="Realizado"),
        ),
        migrations.AddField(
            model_name="shipmentstage",
            name="estimated_completion",
            field=models.DateField(blank=True, null=True, verbose_name="Previsto"),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRE", "Pré-Embarque"),
                    ("RDY", "Pronto p/ Embarque"),
                    ("SHP", "Embarcado"),
                ],
                default="PRE",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="shipmentbatch",
            name="loaded_quantity",
            field=models.PositiveIntegerField(verbose_name="Qtde Carregada"),
        ),
        migrations.AlterField(
            model_name="shipmentstage",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="shipment_stages/%Y/%m/%d/",
                verbose_name="Anexo",
            ),
        ),
        migrations.AlterField(
            model_name="shipmentstage",
            name="completed",
            field=models.BooleanField(default=False, verbose_name="Concluído"),
        ),
        migrations.AlterField(
            model_name="shipmentstage",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Observações"),
        ),
        migrations.AlterField(
            model_name="stage",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Etapa"),
        ),
        migrations.AlterField(
            model_name="stage",
            name="workflow",
            field=models.CharField(
                choices=[("PRE", "Pré-Embarque"), ("SHP", "Embarque Final")],
                max_length=3,
            ),
        ),
    ]
