# Generated by Django 5.2.3 on 2025-07-24 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0002_delete_finalshipment_delete_preshipment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipmentbatch",
            name="loaded_quantity",
        ),
        migrations.RemoveField(
            model_name="shipmentstage",
            name="completed",
        ),
        migrations.AddField(
            model_name="shipmentbatch",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="shipmentstage",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="stage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRE", "Pre-Loading"),
                    ("RDY", "Ready to Load"),
                    ("SHP", "Shipped"),
                ],
                default="PRE",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="stage",
            name="workflow",
            field=models.CharField(
                choices=[("PRE", "Pre-Loading"), ("SHP", "Shipment")], max_length=3
            ),
        ),
    ]
