# Generated by Django 5.2.3 on 2025-07-25 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0003_remove_shipmentbatch_loaded_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="agents_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="booking",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="booking_document/%Y/%m/%d/",
                verbose_name="Booking Document",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="shipment",
            name="cons_point",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Consolidation Point"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="destination_agent",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Destination Agent"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="loading_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="origin_agent",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Origin Agent"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shp_doc",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="shipment_document/%Y/%m/%d/",
                verbose_name="Shipping Document",
            ),
        ),
        migrations.AddField(
            model_name="stage",
            name="allows_attachment",
            field=models.BooleanField(
                default=True,
                help_text="If not checked, do not show the attachment field",
            ),
        ),
        migrations.AddField(
            model_name="stage",
            name="requires_attachment",
            field=models.BooleanField(
                default=False,
                help_text="If checked, turns attachment field requireds when actual_completion=True",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="carrier",
            field=models.CharField(blank=True, max_length=200, verbose_name="Carrier"),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="tracking_number",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Tracking Number"
            ),
        ),
        migrations.AlterField(
            model_name="shipmentstage",
            name="actual_completion",
            field=models.DateField(blank=True, null=True, verbose_name="Actual"),
        ),
        migrations.AlterField(
            model_name="shipmentstage",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="shipment_stages/%Y/%m/%d/",
                verbose_name="Attachment",
            ),
        ),
        migrations.AlterField(
            model_name="shipmentstage",
            name="estimated_completion",
            field=models.DateField(blank=True, null=True, verbose_name="Estimated"),
        ),
        migrations.AlterField(
            model_name="shipmentstage",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Observations"),
        ),
        migrations.CreateModel(
            name="StageShipmentField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Ex: loading_date, bl_number, origin_agent…",
                        max_length=100,
                        verbose_name="Nome do campo em Shipment",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_configs",
                        to="shipments.stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campo de Shipment por Etapa",
                "verbose_name_plural": "Campos de Shipment por Etapa",
                "unique_together": {("stage", "field_name")},
            },
        ),
    ]
