# Generated by Django 5.2.3 on 2025-07-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shipments",
            "0004_shipment_agents_note_shipment_booking_shipment_city_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="pod",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Port of Destination"
            ),
        ),
    ]
