# Generated by Django 5.2.3 on 2025-07-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_alter_batchstage_options_alter_stage_options_and_more"),
        ("shipments", "0005_shipment_pod"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shipmentbatch",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="shipmentbatch",
            constraint=models.UniqueConstraint(
                fields=("order_batch",), name="unique_order_batch_per_shipment"
            ),
        ),
    ]
