# Generated by Django 5.2.3 on 2025-07-29 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_alter_batchstage_options_alter_stage_options_and_more"),
        ("shipments", "0006_alter_shipmentbatch_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="shipmentbatch",
            name="unique_order_batch_per_shipment",
        ),
        migrations.AlterUniqueTogether(
            name="shipmentbatch",
            unique_together={("shipment", "order_batch")},
        ),
    ]
