# Generated by Django 5.2.3 on 2025-08-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shipments",
            "0007_remove_shipmentbatch_unique_order_batch_per_shipment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="ata_destination",
            field=models.DateField(blank=True, null=True, verbose_name="A.T.A"),
        ),
        migrations.AddField(
            model_name="shipment",
            name="bl_date",
            field=models.DateTimeField(null=True, verbose_name="B.L Date"),
        ),
        migrations.AddField(
            model_name="shipment",
            name="bl_number",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="B.L Number"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="eta_destination",
            field=models.DateField(blank=True, null=True, verbose_name="E.T.A"),
        ),
        migrations.AddField(
            model_name="shipment",
            name="inspection_no",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Inspection Number"
            ),
        ),
    ]
