# Generated by Django 5.2.3 on 2025-10-18 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agent_carrier'),
        ('shipments', '0008_shipment_ata_destination_shipment_bl_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='carrier',
            field=models.ForeignKey(blank=True, max_length=200, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='core.carrier', verbose_name='Carrier'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='city',
            field=models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.PROTECT, related_name='shipments_city', to='core.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='cons_point',
            field=models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.PROTECT, related_name='shipments_cons_point', to='core.city', verbose_name='Consolidation Point'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='destination_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_destination', to='core.agent', verbose_name='Destination Agent'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='origin_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_origin', to='core.agent', verbose_name='Origin Agent'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='pod',
            field=models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.PROTECT, related_name='shipments_pod', to='core.port', verbose_name='Port of Destination'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='pol',
            field=models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.PROTECT, related_name='shipments_pol', to='core.port', verbose_name='Port of Loading'),
        ),
    ]
